// SPDX-License-Identifier: Apache-2.0

// define my own layer variable names

#define ARDUX_ADJ_LAYER_BASE ARDUX_ADJ_LAYER_BASE_LEFT
#define ARDUX_ADJ_LAYER_NUM ARDUX_ADJ_LAYER_NUM_LEFT
#define ARDUX_ADJ_LAYER_SYM ARDUX_ADJ_LAYER_SYM_LEFT
#define ARDUX_ADJ_LAYER_PAR ARDUX_ADJ_LAYER_PAR_LEFT
#define ARDUX_ADJ_LAYER_NUMLOCK ARDUX_ADJ_LAYER_NUMLOCK_LEFT
#define ARDUX_ADJ_LAYER_AKEYS ARDUX_ADJ_LAYER_AKEYS_LEFT
#define ARDUX_ADJ_LAYER_MSE ARDUX_ADJ_LAYER_MSE_LEFT
#define ARDUX_ADJ_LAYER_CTRL ARDUX_ADJ_LAYER_CTRL_LEFT