// SPDX-License-Identifier: Apache-2.0

// define my own layer variable names

#define ARDUX_ADJ_LAYER_BASE ARDUX_ADJ_LAYER_BASE_LEFT
#define ARDUX_ADJ_LAYER_NUM ARDUX_ADJ_LAYER_NUM_LEFT
#define ARDUX_ADJ_LAYER_SYM ARDUX_ADJ_LAYER_SYM_LEFT
#define ARDUX_ADJ_LAYER_PAR ARDUX_ADJ_LAYER_PAR_LEFT
#define ARDUX_ADJ_LAYER_NAV ARDUX_ADJ_LAYER_NAV_LEFT
#define ARDUX_ADJ_LAYER_CUS ARDUX_ADJ_LAYER_CUS_LEFT
#define ARDUX_ADJ_LAYER_MSE ARDUX_ADJ_LAYER_MSE_LEFT